### ISSUE TITLE
Recording transfer doesn't work. scalelite_post_publish.rb 

### ISSUE THREAD

**Issue by eemirtekin** [blindsidenetworks/scalelite#1067]
Hi All,

I use BBB 2.7.5 and Scalelite 1.5.1.7.

When I run the below command [1]on BBB server, I get the error below [2].

[1]

`cd /usr/local/bigbluebutton/core/scripts  && sudo -n -u bigbluebutton -g scalelite-spool ruby ./post_publish/scalelite_post_publish.rb -m 7808b90456a7f71eee497350f26f7ce2fece9526-1715687769411`

[2]

```
Traceback (most recent call last):
        8: from scalelite_post_publish.rb:23:in `<main>'
        7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)
```

**Comment by akhmetbay** [comment]
try this one:

sudo apt install ruby2.7-dev libsystemd-dev
sudo gem install redis builder
sudo gem install nokogiri -v 1.15.5
sudo gem install loofah open4 absolute_time journald-logger

**Comment by JamesH1978** [comment]
I have the same issue, while running the batch import script or post publih, and when it try to install libsystemd-dev, i get a load of permission denied and fails out. 
`BigBlueButton Server 2.7.4 (625)
                    Kernel version: 5.4.0-182-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
`

`
root@vsbbb2:/usr/local/bigbluebutton/core/scripts# sudo apt install ruby2.7-dev libsystemd-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsystemd-dev is already the newest version (245.4-4ubuntu3.23).
ruby2.7-dev is already the newest version (2.7.0-5ubuntu1.13).
ruby2.7-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up bbb-record-core (1:2.7-15) ...
chown: changing ownership of '/var/bigbluebutton/recording/status': Operation not permitted
dpkg: error processing package bbb-record-core (--configure):
 installed bbb-record-core package post-installation script subprocess returned error exit status 1
Setting up bbb-learning-dashboard (1:2.7-12) ...
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/favicon.ico': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/index.html': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/media/bbb-icons.1b4ec364994645317829.woff': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/media': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css/main.43651e12.css.map': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css/main.43651e12.css': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js.LICENSE.txt': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js.map': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/asset-manifest.json': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/': Operation not permitted
dpkg: error processing package bbb-learning-dashboard (--configure):
 installed bbb-learning-dashboard package post-installation script subprocess returned error exit status 1
Setting up bbb-config (1:2.7-32) ...
...chown: changing ownership of '/var/bigbluebutton/recording/publish/presentation': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/publish': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/processed': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/sanity': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/recorded': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/published': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/ended': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/archived': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/raw': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/process': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording': Operation not permitted
dpkg: error processing package bbb-config (--configure):
 installed bbb-config package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 bbb-record-core
 bbb-learning-dashboard
 bbb-config
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by akhmetbay** [comment]
Your disk may be mounted as read-only or something wrong with your directory
