### ISSUE TITLE
No such file or directory @ realpath_rec - /mnt/scalelite-recordings

### ISSUE THREAD

**Issue by mattjereb** [blindsidenetworks/scalelite#118]
Service scalelite-recording-importer.service crashes with the error `No such file or directory @ realpath_rec - /mnt/scalelite-recordings`

Folder on the host server exists and other services such as scalelite-api.service scalelite-nginx.service scalelite-poller.service start with the same environment settings.

Don't have much expertise in Docker and could not find the reason of this problem.

```
docker[4021]: v1-recording-importer: Pulling from blindsidenetwks/scalelite
docker[4021]: Digest: sha256:897852c793ad38e605dfc2e728fece67101a6e409ff7bd38bcae1d7c4769872c
docker[4021]: Status: Image is up to date for blindsidenetwks/scalelite:v1-recording-importer
docker[4021]: docker.io/blindsidenetwks/scalelite:v1-recording-importer
systemd[1]: Started Scalelite Recording Importer.
docker[4044]: I, [2020-04-03T07:22:31.003000 #6]  INFO -- : Monitoring /mnt/scalelite-recordings/var/bigbluebutton/spool for new recording files
docker[4044]: rake aborted!
docker[4044]: Errno::ENOENT: No such file or directory @ realpath_rec - /mnt/scalelite-recordings
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:17:in 'realpath'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:17:in 'block in initialize'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:16:in 'map'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:16:in 'initialize'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/backend.rb:25:in 'new'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/backend.rb:25:in 'initialize'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:47:in 'new'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:47:in 'initialize'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen.rb:41:in 'new'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen.rb:41:in 'to'
docker[4044]: /srv/scalelite/lib/tasks/recordings.rake:14:in 'block (2 levels) in <main>'
docker[4044]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in '<top (required)>'
docker[4044]: /usr/bin/bundle:23:in 'load'
docker[4044]: /usr/bin/bundle:23:in '<main>'
docker[4044]: Tasks: TOP => recordings:watch
docker[4044]: (See full trace by running task with --trace)
systemd[1]: scalelite-recording-importer.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: scalelite-recording-importer.service: Failed with result 'exit-code'.
```

part of the /etc/default/scalelite
```
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly

RECORDING_SPOOL_DIR=/mnt/scalelite-recordings/var/bigbluebutton/spool
RECORDING_WORK_DIR=/mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
RECORDING_PUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/published
RECORDING_UNPUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/unpublished
```

**Comment by mattjereb** [comment]
Attached a service status output:
```
scalelite-recording-importer.service - Scalelite Recording Importer
   Loaded: loaded (/etc/systemd/system/scalelite-recording-importer.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-04-03 07:57:32 UTC; 23s ago
  Process: 5786 ExecStart=/usr/bin/docker run --name scalelite-recording-importer --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_DIR},target=/var/bigbluebutton blindsidenetwks/scaleli
  Process: 5691 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer (code=exited, status=0/SUCCESS)
  Process: 5595 ExecStartPre=/usr/bin/docker rm scalelite-recording-importer (code=exited, status=0/SUCCESS)
  Process: 5546 ExecStartPre=/usr/bin/docker kill scalelite-recording-importer (code=exited, status=1/FAILURE)
 Main PID: 5786 (code=exited, status=1/FAILURE)
```

Ubuntu 18.04
Linux sl.aih.nsw.edu.au 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mattjereb** [comment]
Can it be a problem because of the mount point?
mount
...
/dev/nvme0n1p1 on /mnt/scalelite-recordings type ext4 (rw,relatime,data=ordered)
...

**Comment by rabser** [comment]
Taking a look at my config files, i don't have these four lines in /etc/default/scalelite:
```
RECORDING_SPOOL_DIR=/mnt/scalelite-recordings/var/bigbluebutton/spool
RECORDING_WORK_DIR=/mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
RECORDING_PUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/published
RECORDING_UNPUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/unpublished
```
because they modify the internal paths of the services, and if don't change something inside the dockers, you should left them to the default values (or better do not define at all).

Remove them from /etc/default/scalelite, restart services (all...) and all should go fine.

**Comment by mattjereb** [comment]
That was it! Thank you very much. 

Don't know how I've read the manuals :)
