### ISSUE TITLE
Some commands not working when any of the servers is not responding

### ISSUE THREAD

**Issue by baltuonis** [blindsidenetworks/scalelite#134]
`getMeetings` and `rake status` will crash in case when any of BBB servers (even disabled) do not respond (e.g. offline/maintenace)

```
Errno::ECONNREFUSED: Failed to open TCP connection to myfancyserver.com:443 (Connection refused - connect(2) for "myfancyserver.com" port 443)
/srv/scalelite/app/controllers/concerns/api_helper.rb:49:in `get_post_req'
/srv/scalelite/lib/tasks/status.rake:11:in `block (2 levels) in <main>'
/srv/scalelite/lib/tasks/status.rake:10:in `each'
/srv/scalelite/lib/tasks/status.rake:10:in `block in <main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for "myfancyserver.com" port 443
/srv/scalelite/app/controllers/concerns/api_helper.rb:49:in `get_post_req'
/srv/scalelite/lib/tasks/status.rake:11:in `block (2 levels) in <main>'
/srv/scalelite/lib/tasks/status.rake:10:in `each'
/srv/scalelite/lib/tasks/status.rake:10:in `block in <main>'
Tasks: TOP => status
(See full trace by running task with --trace)
```

**Comment by canmese** [comment]
Hello,
I had a similar problem. I installed both postgres and redis databases on the scalelite server, but I could not establish a connection. can you recommend any guideline for instruction to connect to database.

**Comment by baltuonis** [comment]
I think this is related with #94 
So we should wait for the next release and maybe close this

**Comment by farhatahmad** [comment]
Yeah this is already fixed and will be included in the next release
