### ISSUE TITLE
The reguested meeting does not exist

### ISSUE THREAD

**Issue by gethanos** [blindsidenetworks/scalelite#148]
Hi,
I have 3 BBB Servers and a moodle Instance with many courses and groups for students. I have also setup a dedicated VM with scalelite. 
It seems that randomly, but very often i get "bigbluebuttonbn/unreachable" page on moodle and on the API i get logs like:
` [d221244f-590f-4d10-be53-f12c4980e944] The requested meeting 2260ee07763ee8f8a0bd8ef0057b52215332b694-184-287[719] does not exist`

if someone else joins on another class a server and I jump to another server (i think that's when it happens), I manage to enter the bbb room. Any ideas?

Bests

**Comment by gethanos** [comment]
I tried to clean up the moodle database from meeting IDs, also i tried to join from courses without groups, and also with older version of the Moodle Plugin. Also different Moodle instance. Same behavior, I also installed a fresh scalelite server to test. 

Anything left to test?
Bests

**Comment by gethanos** [comment]
Just an update:
After a lot of tests, it seems that after i renamed a students group in order not to have any Greek characters, but only latin, the specific Room have work! Is there something wrong with encoding that might causing issues like those?
There are some rooms that will work after you "hit" one, two times the Join the Meeting, but for some, it;s just impossible to join. This Room that i am talking about was one of them.

**Comment by IamLuksha** [comment]
I have the same problem.
On logs scalelite saw a 400 error. Changed the name of the rally and earned.
It seems to me encoding problems. Course Names Use Cyrillic

help us please
@farhatahmad @ffdixon @jfederico

**Comment by IamLuksha** [comment]
I took an http request from scalelite logs to create a meeting

Changed checksum using the secret of one of the BBB servers managed by Scalelite.

Fulfilled this request and the room was created.

Apparently, something is lost during the checksum replacement.
But I have not yet found at what step. But the first does not reach BBB servers. He is rejected by Scalelite

**Comment by gethanos** [comment]
I managed to make it work by recreating every bigbluebuttonbn activity in the courses. few times i had to do it twice or even more. Most Courses now work, but randomly especially in courses with group names that contain Greek & Special characters (like"-") and numbers are getting rejected again with "bigbluebuttonbn/unreachable" error.

Bests!

**Comment by IamLuksha** [comment]
```
Started GET "/bigbluebutton/api/getMeetingInfo?&meetingID=0db363a8d441dc87b55adf3cf25e075cff4f93d7-34-34&checksum=78ee4c542e7d8c341abb0e286d7db964a8460db3" for 217.21.43.59 at 2020-04-15 17:41:25 +0000
I, [2020-04-15T17:41:25.951225 #6]  INFO -- : [12c02137-8bbf-4f6a-9e10-ec6b91e5f093] Processing by BigBlueButtonApiController#get_meeting_info as XML
I, [2020-04-15T17:41:25.951443 #6]  INFO -- : [12c02137-8bbf-4f6a-9e10-ec6b91e5f093]   Parameters: {"meetingID"=>"0db363a8d441dc87b55adf3cf25e075cff4f93d7-34-34", "checksum"=>"78ee4c542e7d8c341abb0e286d7db964a8460db3"}
I, [2020-04-15T17:41:25.953827 #6]  INFO -- : [12c02137-8bbf-4f6a-9e10-ec6b91e5f093] The requested meeting 0db363a8d441dc87b55adf3cf25e075cff4f93d7-34-34 does not exist
I, [2020-04-15T17:41:25.954992 #6]  INFO -- : [12c02137-8bbf-4f6a-9e10-ec6b91e5f093] Completed 200 OK in 3ms (Views: 0.4ms | Allocations: 313)
I, [2020-04-15T17:41:25.979677 #6]  INFO -- : [4427d3d5-939c-46e4-9470-67ba6434bf18] Started GET "/bigbluebutton/api/create?&meetingID=0db363a8d441dc87b55adf3cf25e075cff4f93d7-34-34&name=%D0%9B%D0%B5%D0%BA%D1%86%D0%B8%D0%B8-%D0%B2%D0%B5%D0%B1%D0%B8%D0%BD%D0%B0%D1%80%D1%8B+%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D0%B5%D0%BB%D1%8C%D1%86%D0%B5%D0%B2%D0%B0+%D0%98.%D0%90.+%28%D0...&attendeePW=%21Uq%28LR5J%29V%26g&moderatorPW=NUX9YP2m%29%3FI3&logoutURL=https%3A%2F%2Fmoodletest.bsu.by%2Fmod%2Fbigbluebuttonbn%2Fbbb_view.php%3Faction%3Dlogout%26id%3D589%26bn%3D34&record=false&welcome=%3Cbr%3E%D0%94%D0%BE%D0%B1%D1%80%D0%BE+%D0%BF%D0%BE%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C+%D0%BD%D0%B0+%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%B8%D0%B5+%3Cb%3E%C2%AB%25%25CONFNAME%25%25%C2%BB%3C%2Fb%3E%21%3Cbr%3E%3Cbr%3E%D0%A7%D1%82%D0%BE%D0%B1%D1%8B+%D1%80%D0%B0%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D1%8C%D1%81%D1%8F%2C+%D0%BA%D0%B0%D0%BA+%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F+%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BE%D0%B9+BigBlueButton%2C+%D0%92%D1%8B+%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%D0%B5+%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C+%3Ca+href%3D%22event%3Ahttp%3A%2F%2Fwww.bigbluebutton.org%2Fcontent%2Fvideos%22%3E%3Cu%3E%D0%BE%D0%B1%D1%83%D1%87%D0%B0%D1%8E%D1%89%D0%B8%D0%B5+%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%3C%2Fu%3E%3C%2Fa%3E+%28%D0%BD%D0%B0+%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%BC+%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5%29.%3Cbr%3E%3Cbr%3E%D0%94%D0%BB%D1%8F+%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D1%8F+%D0%B2+%D0%B0%D1%83%D0%B4%D0%B8%D0%BE%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D0%B8+%D0%BD%D0%B0%D0%B6%D0%BC%D0%B8%D1%82%D0%B5+%D0%BD%D0%B0+%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5+%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9+%D0%B3%D0%B0%D1%80%D0%BD%D0%B8%D1%82%D1%83%D1%80%D1%8B+%28%D0%BD%D0%B0%D1%83%D1%88%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%29+%D0%B2+%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%BC+%D0%BB%D0%B5%D0%B2%D0%BE%D0%BC+%D1%83%D0%B3%D0%BB%D1%83.+%3Cb%3E%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B9%D1%82%D0%B5+%D0%B3%D0%B0%D1%80%D0%BD%D0%B8%D1%82%D1%83%D1%80%D1%83%2C+%D1%87%D1%82%D0%BE%D0%B1%D1%8B++%D1%83%D0%B1%D0%B5%D1%80%D0%B5%D1%87%D1%8C+%D1%81%D0%B5%D0%B1%D1%8F+%D0%B8+%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D1%85+%D0%BE%D1%82+%D0%BD%D0%B5%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%BD%D0%BE%D0%B3%D0%BE+%D0%B3%D1%83%D0%BB%D0%B0.%3C%2Fb%3E&meta_bbb-origin=Moodle&meta_bbb-origin-version=3.7.2+%28Build%3A+20190909%29&meta_bbb-origin-server-name=moodletest.bsu.by&meta_bbb-origin-server-common-name=&meta_bbb-origin-tag=moodle-mod_bigbluebuttonbn+%282019042008%29&meta_bbb-context=%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5+BigBlueButton&meta_bbb-recording-name=%D0%9B%D0%B5%D0%BA%D1%86%D0%B8%D0%B8-%D0%B2%D0%B5%D0%B1%D0%B8%D0%BD%D0%B0%D1%80%D1%8B+%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D0%B5%D0%BB%D1%8C%D1%86%D0%B5%D0%B2%D0%B0+%D0%98.%D0%90.+%28%D0...&meta_bbb-recording-description=&meta_bbb-recording-tags=&checksum=cda649c4c5b565104963a87066a88421c033a6e9" for 217.21.43.59 at 2020-04-15 17:41:25 +0000
F, [2020-04-15T17:41:25.985576 #6] FATAL -- : [4427d3d5-939c-46e4-9470-67ba6434bf18]   
[4427d3d5-939c-46e4-9470-67ba6434bf18] ActionController::BadRequest (Invalid query parameters: Invalid encoding for parameter: Лекции-вебинары Новосельцева И.А. (�...):
[4427d3d5-939c-46e4-9470-67ba6434bf18]   
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/request/utils.rb:39:in `check_param_encoding'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/request/utils.rb:34:in `block in check_param_encoding'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/request/utils.rb:34:in `each_value'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/request/utils.rb:34:in `check_param_encoding'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/http/request.rb:370:in `block in GET'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/request.rb:69:in `fetch'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/request.rb:69:in `fetch_header'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/http/request.rb:367:in `GET'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/http/parameters.rb:55:in `parameters'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:23:in `process_action'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activerecord (6.0.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/abstract_controller/base.rb:136:in `process'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionview (6.0.2.1) lib/action_view/rendering.rb:39:in `process'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_controller/metal.rb:191:in `dispatch'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_controller/metal.rb:252:in `dispatch'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/etag.rb:27:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/head.rb:12:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
[4427d3d5-939c-46e4-9470-67ba6434bf18] railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
[4427d3d5-939c-46e4-9470-67ba6434bf18] railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/runtime.rb:22:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] puma (4.3.3) lib/puma/configuration.rb:228:in `call'
[4427d3d5-939c-46e4-9470-67ba6434bf18] puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
[4427d3d5-939c-46e4-9470-67ba6434bf18] puma (4.3.3) lib/puma/server.rb:472:in `process_client'
[4427d3d5-939c-46e4-9470-67ba6434bf18] puma (4.3.3) lib/puma/server.rb:328:in `block in run'
[4427d3d5-939c-46e4-9470-67ba6434bf18] puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by IamLuksha** [comment]
This helped me
It turns out the symbol is cut in half

https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/issues/193

https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/194/commits/902fd2ff1f770dd245a4428eb88a8b8fef0fb71e

**Comment by farhatahmad** [comment]
Looks like this was fixed through moodle, so I'll close this
