### ISSUE TITLE
Stuck Setting up Scalelite (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by jainvipin69** [blindsidenetworks/scalelite#283]
Hi,

Please advice what is wrong in my setup, I am getting below:

scalelite-api.service - Scalelite API
   Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-07-21 07:41:43 UTC; 2min 21s ago
  Process: 11983 ExecStart=/usr/bin/docker run --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_DIR},target
  Process: 11964 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=0/SUCCESS)
  Process: 11951 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=0/SUCCESS)
  Process: 11938 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)
 Main PID: 11983 (code=exited, status=1/FAILURE)

Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:98:in `run'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
Jul 21 07:41:43 ip-172-31-31-6 docker[11983]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
Jul 21 07:41:43 ip-172-31-31-6 systemd[1]: scalelite-api.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 07:41:43 ip-172-31-31-6 systemd[1]: scalelite-api.service: Unit entered failed state.
Jul 21 07:41:43 ip-172-31-31-6 systemd[1]: scalelite-api.service: Failed with result 'exit-code'.

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-07-21 07:41:44 UTC; 2min 20s ago
  Process: 12192 ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,sour
  Process: 12040 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 12004 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 11984 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 12192 (code=exited, status=1/FAILURE)

Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: Startup script was run as init, re-execing using tini.
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: Generating templated nginx configuration...
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: Using non-SSL configuration template.
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: Starting nginx periodic reload process...
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: Starting nginx...
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: 2020/07/21 07:41:44 [emerg] 7#7: host not found in upstream "scalelite-api" in /etc/nginx/conf.d/scalelite.common:2
Jul 21 07:41:44 ip-172-31-31-6 docker[12192]: nginx: [emerg] host not found in upstream "scalelite-api" in /etc/nginx/conf.d/scalelite.common:2
Jul 21 07:41:44 ip-172-31-31-6 systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 07:41:44 ip-172-31-31-6 systemd[1]: scalelite-nginx.service: Unit entered failed state.
Jul 21 07:41:44 ip-172-31-31-6 systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.

**Comment by jainvipin69** [comment]
Content of /etc/default/scalelite

URL_HOST=xxxxxxx
SECRET_KEY_BASE=xxxxxxxx
LOADBALANCER_SECRET=xxxxxxxxxx
DATABASE_URL=postgresql://xxxxxx
REDIS_URL=redis://xxxxxx
SCALELITE_TAG=v1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
