### ISSUE TITLE
"scalelite-poller" stops automatically

### ISSUE THREAD

**Issue by mailalaki** [blindsidenetworks/scalelite#310]
hi, the `scalelite-poller` service on my server stops automatically!
This is its Log:

```
Aug 27 05:48:36 irmesbah-sl docker[9815]: I, [2020-08-27T01:18:34.677275 #6]  INFO -- : Server id=0a84ca25-8228-4ba7-a725-c37a8e13cde9 online load: unavailable
Aug 27 05:48:36 irmesbah-sl docker[9815]: rake aborted!
Aug 27 05:48:36 irmesbah-sl docker[9815]: Redis::TimeoutError: Connection timed out
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/hiredis.rb:58:in `rescue in read'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/hiredis.rb:53:in `read'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:272:in `block in read'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:260:in `io'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:271:in `read'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `block in call'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:241:in `block (2 levels) in process'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:384:in `ensure_connected'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:2140:in `block in hmset'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:2139:in `hmset'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:469:in `call_with_namespace'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:349:in `block (2 levels) in <class:Namespace>'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/app/models/server.rb:135:in `block in reset_healthy_counter'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/app/models/application_redis_record.rb:133:in `block in with_connection'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/redis_store.rb:35:in `block in with_connection'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/redis_store.rb:35:in `with_connection'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/app/models/application_redis_record.rb:132:in `with_connection'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/app/models/application_redis_record.rb:136:in `with_connection'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/app/models/server.rb:134:in `reset_healthy_counter'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/tasks/poll.rake:56:in `rescue in block (3 levels) in <main>'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/tasks/poll.rake:52:in `block (3 levels) in <main>'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/tasks/poll.rake:32:in `each'
Aug 27 05:48:36 irmesbah-sl docker[9815]: /srv/scalelite/lib/tasks/poll.rake:32:in `block (2 levels) in <main>'
```
Can anyone help to solve this problem?

**Comment by frahman80** [comment]
Seems like you lost connection with Redis server.

**Comment by mailalaki** [comment]
yes,
i setup Radis on the same server (scalelite server) with Docker and now I realize that I had this log at the same time in `scalelite-redis.service`:

```
Aug 28 16:16:49 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 11:46:49.188 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
Aug 28 16:16:49 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 11:46:49.188 # Server initialized
Aug 28 16:16:49 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 11:46:49.705 * DB loaded from append only file: 0.516 seconds
Aug 28 16:16:49 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 11:46:49.705 * Ready to accept connections
Aug 29 01:28:27 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 20:58:27.063 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
Aug 29 01:36:21 irmesbah-sl docker[31747]: 1:M 28 Aug 2020 21:06:21.055 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
```

1. `WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.`
2. `Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.`
What is the solution for these two?

**Comment by mailalaki** [comment]
for the first, editing this `/proc/sys/net/core/somaxconn` had no effect!

**Comment by frahman80** [comment]
I would suggest to check your connection with redis-cli first then delve deeper.

**Comment by defnull** [comment]
I had the same problem with the recordings-importer. A temporary database error (in my case `Failed to import recording: PG::UnableToSend: no connection to the server`) caused the rake task to stop working, but not to terminate, so it was not restarted and monitoring thought everything was okay.
The task should either gracefully handle these errors and continue working, or terminate and let docker-compose/systemd restart the task.
