### ISSUE TITLE
Invalid encoding error

### ISSUE THREAD

**Issue by marcinroman** [blindsidenetworks/scalelite#314]
There is "invalid encoding" error when creating meeting with name containing nonascii characters.

Bigbluebutton 2.2.23, scalelite 1.0.6 running on docker.

```
scalelite-api                   | I, [2020-09-03T13:56:09.058429 #10]  INFO -- : [29b20b25-88f0-4c6b-99af-38f48aef6437] Started POST "/bigbluebutton/api/create?&meetingID=14bb90df6917463335b863ab45d673e14c853667-7171-3839&name=Konsultacje+wrze%C5%9Bniowe+2019%2F20&attendeePW=Cvy2%254iL%3B%2CMl&moderatorPW=%3BRg_K%403Xk%3A9S&logoutURL=https%3A%2F%2Fkampus.umcs.pl%2Fmod%2Fbigbluebuttonbn%2Fbbb_view.php%3Faction%3Dlogout%26id%3D159403%26bn%3D3839&record=false&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21%3Cbr%3E%3Cbr%3EFor+help+on+using+BigBlueButton+see+these+%28short%29++%3Ca+href%3D%22event%3Ahttp%3A%2F%2Fwww.bigbluebutton.org%2Fcontent%2Fvideos%22%3E%3Cu%3Etutorial+videos%3C%2Fu%3E%3C%2Fa%3E.%3Cbr%3E%3Cbr%3ETo+join+the+audio+bridge+click+the+phone+icon+%28top+center%29.+%3Cb%3EPlease+use+a+headset+to+avoid+causing+background+noise+for+others.%3C%2Fb%3E&meta_bbb-origin=Moodle&meta_bbb-origin-version=3.5.13+%28Build%3A+20200713%29&meta_bbb-origin-server-name=kampus.umcs.pl&meta_bbb-origin-server-common-name=&meta_bbb-origin-tag=moodle-mod_bigbluebuttonbn+%282019042008%29&meta_bbb-context=e-konsultacje+sesja+wrze%C5%9Bniowa+2019%2F20&meta_bbb-recording-name=Konsultacje+wrze%C5%9Bniowe+2019%2F20&meta_bbb-recording-description=E-konsultacje+dla+student%C3%B3w+wszystkich+kierunk%C3%B3w+w+sesji+wrze%C5...&meta_bbb-recording-tags=&checksum=fb1a9f27d59c83bc7125be7f77073a023347b9c5" for 87.246.207.149 at 2020-09-03 13:56:09 +0000
scalelite-api                   | F, [2020-09-03T13:56:09.073209 #10] FATAL -- : [29b20b25-88f0-4c6b-99af-38f48aef6437]   
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] ActionController::BadRequest (Invalid query parameters: Invalid encoding for parameter: E-konsultacje dla studentów wszystkich kierunków w sesji wrze�...):
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437]   
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/request/utils.rb:39:in `check_param_encoding'
scalelite-nginx                 | 87.246.207.149 - - [03/Sep/2020:13:56:09 +0000] "POST /bigbluebutton/api/create?&meetingID=14bb90df6917463335b863ab45d673e14c853667-7171-3839&name=Konsultacje+wrze%C5%9Bniowe+2019%2F20&attendeePW=Cvy2%254iL%3B%2CMl&moderatorPW=%3BRg_K%403Xk%3A9S&logoutURL=https%3A%2F%2Fkampus.umcs.pl%2Fmod%2Fbigbluebuttonbn%2Fbbb_view.php%3Faction%3Dlogout%26id%3D159403%26bn%3D3839&record=false&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21%3Cbr%3E%3Cbr%3EFor+help+on+using+BigBlueButton+see+these+%28short%29++%3Ca+href%3D%22event%3Ahttp%3A%2F%2Fwww.bigbluebutton.org%2Fcontent%2Fvideos%22%3E%3Cu%3Etutorial+videos%3C%2Fu%3E%3C%2Fa%3E.%3Cbr%3E%3Cbr%3ETo+join+the+audio+bridge+click+the+phone+icon+%28top+center%29.+%3Cb%3EPlease+use+a+headset+to+avoid+causing+background+noise+for+others.%3C%2Fb%3E&meta_bbb-origin=Moodle&meta_bbb-origin-version=3.5.13+%28Build%3A+20200713%29&meta_bbb-origin-server-name=kampus.umcs.pl&meta_bbb-origin-server-common-name=&meta_bbb-origin-tag=moodle-mod_bigbluebuttonbn+%282019042008%29&meta_bbb-context=e-konsultacje+sesja+wrze%C5%9Bniowa+2019%2F20&meta_bbb-recording-name=Konsultacje+wrze%C5%9Bniowe+2019%2F20&meta_bbb-recording-description=E-konsultacje+dla+student%C3%B3w+wszystkich+kierunk%C3%B3w+w+sesji+wrze%C5...&meta_bbb-recording-tags=&checksum=fb1a9f27d59c83bc7125be7f77073a023347b9c5 HTTP/2.0" 400 0 "-" "MoodleBot/1.0" "-"
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/request/utils.rb:34:in `block in check_param_encoding'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/request/utils.rb:34:in `each_value'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/request/utils.rb:34:in `check_param_encoding'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/http/request.rb:378:in `block in GET'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/request.rb:69:in `fetch'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/request.rb:69:in `fetch_header'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/http/request.rb:375:in `GET'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/http/parameters.rb:55:in `parameters'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:23:in `process_action'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/etag.rb:27:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/head.rb:12:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] puma (4.3.5) lib/puma/configuration.rb:228:in `call'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] puma (4.3.5) lib/puma/server.rb:472:in `process_client'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] puma (4.3.5) lib/puma/server.rb:328:in `block in run'
scalelite-api                   | [29b20b25-88f0-4c6b-99af-38f48aef6437] puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by marcinroman** [comment]
It seems that upgrading to moodle plugin 2.3.4 resolved this problem.
