### ISSUE TITLE
Transfer over rsync failed

### ISSUE THREAD

**Issue by Davka** [blindsidenetworks/scalelite#400]
When trying to copy the recordings via RSYNC, the transfer fails

```
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - HOST: (Errno::EACCES)
I, [2021-01-15T21:54:09.132964 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
I, [2021-01-15T21:54:09.133028 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
I, [2021-01-15T21:54:09.133083 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
I, [2021-01-15T21:54:09.133141 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
I, [2021-01-15T21:54:09.133205 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
I, [2021-01-15T21:54:09.133261 #10444]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
I, [2021-01-15T21:54:09.133317 #10444]  INFO -- :       from post_publish/scalelite_post_publish.rb:62:in `<main>'

```

After I commented out `FileUtils.mkdir_p (spool_dir)`, the transfer works

**Comment by glu000** [comment]
I have the same problem, see #395 

Removing `FileUtils.mkdir_p (spool_dir)` does not help.

**Comment by atikulbd** [comment]
Current recording importer script **scalelite_post_publish.rb** has issues. Here's the correct one:
```ruby
#!/usr/bin/ruby
# frozen_string_literal: true

# Scalelite recording transfer script

require 'optparse'
require 'psych'
require 'fileutils'

meeting_id = nil
OptionParser.new do |opts|
  opts.on('-m', '--meeting-id MEETING_ID', 'Internal Meeting ID') do |v|
    meeting_id = v
  end
end.parse!
raise 'Meeting ID was not provided' unless meeting_id

props = Psych.load_file(File.join(__dir__, '../bigbluebutton.yml'))
published_dir = props['published_dir'] || raise('Unable to determine published_dir from bigbluebutton.yml')
scalelite_props = Psych.load_file(File.join(__dir__, '../scalelite.yml'))
work_dir = scalelite_props['work_dir'] || raise('Unable to determine work_dir from scalelite.yml')
spool_dir = scalelite_props['spool_dir'] || raise('Unable to determine spool_dir from scalelite.yml')
extra_rsync_opts = scalelite_props['extra_rsync_opts'] || []

puts("Transferring recording for #{meeting_id} to Scalelite")
format_dirs = []
FileUtils.cd(published_dir) do
  format_dirs = Dir.glob("*/#{meeting_id}")
end
if format_dirs.empty?
  puts('No published recording formats found')
  exit
end

format_dirs.each do |format_dir|
  puts("Found recording format: #{format_dir}")
end

archive_file = "#{work_dir}/#{meeting_id}.tar"
begin
  puts('Creating recording archive')
  FileUtils.mkdir_p(work_dir)
  FileUtils.cd(published_dir) do
    system('tar', '--create', '--file', archive_file, *format_dirs) \
      || raise('Failed to create recording archive')
  end

  puts("Transferring recording archive to #{spool_dir}")
  system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_opts} #{archive_file} #{spool_dir}") \
    || raise('Failed to transfer recording archive')
ensure
  FileUtils.rm_f(archive_file)
end
```
And, then make sure the recording spool directory permission is correct as mentioned here:
```
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md
```
Re-run the commands:
```
chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/spool

chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite

chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/published
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/published

chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
```
Should fix the issue.
