### ISSUE TITLE
Could you help me? versio

### ISSUE THREAD

**Issue by mauser8004** [blindsidenetworks/scalelite#547]
Which version is docker TAG vol when you even increased the load by one per meeting?
aka 1 meeting + 1 load
Unfortunately for us, this new balance is not coming in.

I tried a few:
v1.0.9 TAG
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d]
app/models/application_redis_record.rb:106:in `init_with_attributes'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d] app/models/meeting.rb:102:in
`block in find'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d]
app/models/application_redis_record.rb:133:in `block in with_connection'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d] lib/redis_store.rb:35:in `block
in with_connection'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d] lib/redis_store.rb:35:in
`with_connection'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d]
app/models/application_redis_record.rb:132:in `with_connection'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d] app/models/meeting.rb:97:in `find'
May 10 18:03:45 testsc docker[11759]:
[36d90e0d-efce-4c00-a01c-7a4e49aa8d7d]
app/controllers/bigbluebutton_api_controller.rb:27:in `get_meeting_inf

v1.0.8 It also prints errors.

**Comment by amalrails** [comment]
Hi @mauser8004 you can check the releases page and choose the tag you are looking for , here's the [link](https://github.com/blindsidenetworks/scalelite/releases)
