### ISSUE TITLE
Recording importer fails if there is a file handle open on a recording tar.

### ISSUE THREAD

**Issue by Peterburnett** [blindsidenetworks/scalelite#628]
We have a setup with networked filesystems, that moves files into the recording spool once they have been processed by the webserver. We have observed that occasionally scalelite will fail to import a recording, due to a file handle already being open on the tar file, likely due to it still being moved into the filesystem.

The specific error we are seeing in the logs looks like this:

```
I, [2021-08-05T03:49:28.286185 #8]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/xxxxxx.tar
capture/xxxxxx/
capture/xxxxxx/video-js/
capture/xxxxxx/video-js/video-js.min.css
capture/xxxxxx/video-js/video.min.js
capture/xxxxxx/video-js/lang/
capture/xxxxxx/video-js/lang/ar.js
capture/xxxxxx/video-js/lang/es.js
capture/xxxxxx/video-js/lang/fr.js
capture/xxxxxx/video-js/lang/bg.js
capture/xxxxxx/video-js/lang/hr.js
capture/xxxxxx/video-js/lang/sv.js
capture/xxxxxx/video-js/lang/nl.js
capture/xxxxxx/video-js/lang/en.js
capture/xxxxxx/video-js/lang/hu.js
capture/xxxxxx/video-js/lang/pt-BR.js
capture/xxxxxx/video-js/lang/de.js
capture/xxxxxx/video-js/lang/da.js
capture/xxxxxx/video-js/lang/ja.js
capture/xxxxxx/video-js/lang/nn.js
capture/xxxxxx/video-js/lang/cs.js
capture/xxxxxx/video-js/lang/uk.js
capture/xxxxxx/video-js/lang/ca.js
capture/xxxxxx/video-js/lang/zh-CN.js
capture/xxxxxx/video-js/lang/nb.js
capture/xxxxxx/video-js/lang/sr.js
capture/xxxxxx/video-js/lang/zh-TW.js
capture/xxxxxx/video-js/lang/pl.js
capture/xxxxxx/video-js/lang/it.js
capture/xxxxxx/video-js/lang/ko.js
capture/xxxxxx/video-js/lang/el.js
capture/xxxxxx/video-js/lang/fa.js
capture/xxxxxx/video-js/lang/tr.js
capture/xxxxxx/video-js/lang/ru.js
capture/xxxxxx/video-js/lang/ba.js
capture/xxxxxx/video-js/lang/vi.js
capture/xxxxxx/video-js/lang/fi.js
capture/xxxxxx/video-js/font/
capture/xxxxxx/video-js/font/VideoJS.ttf
capture/xxxxxx/video-js/font/VideoJS.svg
capture/xxxxxx/video-js/font/VideoJS.eot
capture/xxxxxx/video-js/font/VideoJS.woff
capture/xxxxxx/css/
capture/xxxxxx/css/normalize.css
capture/xxxxxx/css/capture.css
capture/xxxxxx/js/
capture/xxxxxx/js/popcorn.chattimeline.js
capture/xxxxxx/js/capture.js
capture/xxxxxx/js/popcorn-complete.min.js
capture/xxxxxx/metadata.xml
capture/xxxxxx/index.html
capture/xxxxxx/captions.json
capture/xxxxxx/capture-0.m4v
E, [2021-08-05T03:49:30.930523 #8] ERROR -- : Failed to import recording: Failed to extract tar file: /var/bigbluebutton/spool/xxxxxx.tar
W, [2021-08-05T03:49:30.930708 #8]  WARN -- : /srv/scalelite/lib/recording_importer.rb:23:in `block (2 levels) in import': Failed to extract tar file: /var/bigbluebutton/spool/xxxxxx.tar (RecordingImporter::RecordingImporterError)
	from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	from /srv/scalelite/lib/recording_importer.rb:21:in `block in import'
	from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
	from /srv/scalelite/lib/recording_importer.rb:20:in `import'
	from /srv/scalelite/lib/tasks/recordings.rake:17:in `block (4 levels) in <main>'
	from /srv/scalelite/lib/tasks/recordings.rake:16:in `each'
	from /srv/scalelite/lib/tasks/recordings.rake:16:in `block (3 levels) in <main>'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
	from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

The specific message being returned from the tar command:

`tar: xxx.tar Cannot open: Stale file handle`

This may be due to the polling option used for detecting files in the directory. These files should be checked for a file handle first and then skipped, or retried

**Comment by jaimemejia** [comment]
Interesting.

I'm not completely sure if that situation can be handle programmatly but, have you checked the networking, performance of your NFS or mount options?
