### ISSUE TITLE
Fail to import recordings from spool directory + 404 error when playing

### ISSUE THREAD

**Issue by MrCapitalist** [blindsidenetworks/scalelite#638]
Hi
I'm using lastest version of Moodle and Scalelite (v1.1.7-bionic230-alpine).

Before I haven't any problem. Recently offline videos aren't available to users because when he tries to open them, 404 error page shows!

and there are a lot of .tar files in the spool directory that have not been imported and cleaned!

I see an error in "scalelite-recording-importer" log:

docker logs --tail 150 --follow --timestamps  scalelite-recording-importer

```
2021-08-16T08:43:53.003000292Z D, [2021-08-16T08:43:53.002859 #8] DEBUG -- :   Thumbnail Load (0.5ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC  [["playback_format_id", 160]]
2021-08-16T08:43:53.005766966Z D, [2021-08-16T08:43:53.005646 #8] DEBUG -- :    (1.3ms)  COMMIT
2021-08-16T08:43:53.058489327Z E, [2021-08-16T08:43:53.058227 #8] ERROR -- : Failed to import recording: undefined method `publish_updated' for #<Recording:0x00007f87b5a54bc0>
2021-08-16T08:43:53.058523966Z Did you mean?  published
2021-08-16T08:43:53.058672993Z W, [2021-08-16T08:43:53.058550 #8]  WARN -- : /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3.7/lib/active_model/attribute_methods.rb:432:in `method_missing': undefined method `publish_updated' for #<Recording:0x00007f87b5a54bc0> (NoMethodError)
2021-08-16T08:43:53.058697659Z Did you mean?  published
2021-08-16T08:43:53.058714683Z  from /srv/scalelite/lib/recording_importer.rb:33:in `block (3 levels) in import'
2021-08-16T08:43:53.058720318Z  from /srv/scalelite/lib/recording_importer.rb:25:in `each'
2021-08-16T08:43:53.058725440Z  from /srv/scalelite/lib/recording_importer.rb:25:in `block (2 levels) in import'
2021-08-16T08:43:53.058730598Z  from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
2021-08-16T08:43:53.058735671Z  from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
2021-08-16T08:43:53.058740489Z  from /srv/scalelite/lib/recording_importer.rb:21:in `block in import'
2021-08-16T08:43:53.058745536Z  from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
2021-08-16T08:43:53.058750403Z  from /srv/scalelite/lib/recording_importer.rb:20:in `import'
2021-08-16T08:43:53.058755240Z  from /srv/scalelite/lib/tasks/recordings.rake:17:in `block (4 levels) in <main>'
2021-08-16T08:43:53.058760455Z  from /srv/scalelite/lib/tasks/recordings.rake:16:in `each'
2021-08-16T08:43:53.058765294Z  from /srv/scalelite/lib/tasks/recordings.rake:16:in `block (3 levels) in <main>'
2021-08-16T08:43:53.058770292Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
2021-08-16T08:43:53.058775307Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
2021-08-16T08:43:53.058780341Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
2021-08-16T08:43:53.058785409Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
2021-08-16T08:43:53.058790377Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
2021-08-16T08:43:53.058795347Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
2021-08-16T08:43:53.058800583Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
2021-08-16T08:43:53.058805599Z  from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

How can I fix `undefined method `publish_updated'` error?

**Comment by amalrails** [comment]
@MrCapitalist as mentioned in the release notes you will have to run the `docker exec -t scalelite-api bundle exec rake db:migrate` command to fix this.

**Comment by MrCapitalist** [comment]
Yes, I saw this command in the Scalelite release changelog, run it and my problem was fixed.
Thanks
