### ISSUE TITLE
scalelite-recording-importer failes to import records

### ISSUE THREAD

**Issue by alizamanir** [blindsidenetworks/scalelite#643]
Hello

I have pool of BBB's and they publish their records to NFS shared folder,
in scalelite 1.0.X there where no issue and scalelite was working smoothly,

After updating the 1.0.7 version which was installed using scalelite lazy deployment from jfredeico's document, to 1.1.7.1 and also new fresh installation using systemd method, scalelite dose not imports the records from spool folder,
when checking the logs using "sudo docker container logs scalelite-recording-importer" it shows the following errors:

I, [2021-08-21T14:49:14.917813 #7]  INFO -- : Monitoring /var/bigbluebutton/spool for new recording files
D, [2021-08-21T14:49:14.920371 #7] DEBUG -- : Checking for existing files…
I, [2021-08-21T14:49:14.924145 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/c7fa6261ec17c742a3580631bdc3110f128ef881-1629545321595.tar
E, [2021-08-21T14:49:14.926973 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-84t8w2
I, [2021-08-21T14:49:14.927035 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/5b9df914debf388818cb79f183c1b6bf5de7ff38-1629492779494.tar
E, [2021-08-21T14:49:14.927133 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-1yz3jik
I, [2021-08-21T14:49:14.927210 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/1af43e1a6b117a7089dc8154071d851824971714-1629544665948.tar
E, [2021-08-21T14:49:14.927319 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-n67dit
I, [2021-08-21T14:49:14.927362 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/1068e19b24dcf102f479bdbcdfc722a5e85fb59a-1629373307515.tar
E, [2021-08-21T14:49:14.927445 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-yg9o1j
I, [2021-08-21T14:49:14.927487 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/4f49cdc6239aeb87c1ec6fb4f1e753c05c63e824-1629015864382.tar
E, [2021-08-21T14:49:14.927568 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-1vlgxn0
I, [2021-08-21T14:49:14.927609 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/af08ce183319097305dd9b3e775910ebe65f2c50-1628859506609.tar
E, [2021-08-21T14:49:14.927690 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-kdt396
I, [2021-08-21T14:49:14.927731 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/1382ff59a53e4d5cd70aedc3f39a6c787d2063bc-1629552069805.tar
E, [2021-08-21T14:49:14.927812 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-cdxxgs
I, [2021-08-21T14:49:14.927853 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/dab719fff9875b557c4105a81abc6418a1c39a74-1629203462553.tar
E, [2021-08-21T14:49:14.927933 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-14k4vtu

D, [2021-08-21T14:49:14.936854 #7] DEBUG -- : Starting file monitor…

can you help me to resolve this issue?

the dontent of "/etc/default/scalelite" is as follow:
---------------------------------------------------------------------------
URL_HOST=XXXXX
SECRET_KEY_BASE=XXXXX
LOADBALANCER_SECRET=XXXXX
DATABASE_URL=postgresql://scalelite:XXXXX@XXXXX:5432
REDIS_URL=redis://:XXXXX@XXXXX:6379
SCALELITE_TAG=v1.1-bionic230-amazonlinux
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly

**Comment by pielonet** [comment]
Hi, did you migrate your database :

```
docker exec -t scalelite-api bundle exec rake db:migrate
```

**Comment by alizamanir** [comment]
hello

I had tested the 
docker exec -t scalelite-api bundle exec rake db:migrate
but there were no cahnge

also I tested the 
docker exec -t scalelite-api bundle exec rake db:downgrade 
and again
docker exec -t scalelite-api bundle exec rake db:migrate

but the issue still exists.

**Comment by alizamanir** [comment]
In new logs, the following new error appears:

I, [2021-08-21T16:06:15.008390 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/6eb53d87cabc88456b760fcb8f691fcd61c192d9-1629551814217.tar
E, [2021-08-21T16:06:15.010079 #7] ERROR -- : Failed to import recording: No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-1q5data
W, [2021-08-21T16:06:15.010214 #7]  WARN -- : /usr/share/ruby/tmpdir.rb:89:in `mkdir': No such file or directory @ dir_s_mkdir - /var/bigbluebutton/recording/scalelite/d20210821-7-1q5data (Errno::ENOENT)
        from /usr/share/ruby/tmpdir.rb:89:in `block in mktmpdir'
        from /usr/share/ruby/tmpdir.rb:135:in `create'
        from /usr/share/ruby/tmpdir.rb:87:in `mktmpdir'
        from /srv/scalelite/lib/recording_importer.rb:20:in `import'
        from /srv/scalelite/lib/tasks/recordings.rake:17:in `block (4 levels) in <main>'
        from /srv/scalelite/lib/tasks/recordings.rake:16:in `each'
        from /srv/scalelite/lib/tasks/recordings.rake:16:in `block (3 levels) in <main>'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
        from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

**Comment by pielonet** [comment]
Hi,
I had a similar issue these days trying to connect scalelite-recording-importer to an SSHFS storage backend.
The docker container failed with this error :
```
Dec 10 10:49:30 dne-t-bbb-24-scalelite docker[8053]: rake aborted!
Dec 10 10:49:30 dne-t-bbb-24-scalelite docker[8053]: Errno::EEXIST: File exists @ dir_s_mkdir - /var/bigbluebutton
Dec 10 10:49:30 dne-t-bbb-24-scalelite docker[8053]: /srv/scalelite/lib/tasks/recordings.rake:9:in `block (2 levels)
```
As the documentation tells (https://apidock.com/ruby/FileUtils/mkdir_p) it is mostly linked to a permissions issue rather than to a missing file.
I then added the mount option "allow_other" to sshfs (it is a fuse option) and it fixed the issue.
