### ISSUE TITLE
Failed to import recording past the change of tag regarding certificate issue

### ISSUE THREAD

**Issue by panosva** [blindsidenetworks/scalelite#693]
I know this issue has been discussed before and should be fixed by running.
docker exec -i scalelite-api bundle exec rake db:migrate
but in my case it did not work. 
Probably i have changed something while looking for solution for the 30th of Sept certificate issue
which made all BBBs offline.

So eventually i did changed the tag:
from: SCALELITE_TAG=v1.2-bionic230-amazonlinux
to: SCALELITE_TAG=v1.2
then restarted the service, pulled the new images
and BBBs came back on line.
Then i run 
docker exec -i scalelite-api bundle exec rake db:migrate
and then restarted the service again.

Recordings come to the spool dir via NFS ok but remain there. Postgres has 1074 rows.

The error i get by running 
docker logs scalelite-recording-importer 
 is:
E, [2021-10-05T18:55:03.841649 #7] ERROR -- : Failed to import recording: undefined method `publish_updated' for #<Recording:0x00007f2133d50a38>
Did you mean?  published
W, [2021-10-05T18:55:03.841792 #7]  WARN -- : /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.4.1/lib/active_model/attribute_methods.rb:432:in `method_missing': undefined method `publish_updated' for #<Recording:0x00007f2133d50a38> (NoMethodError)
Did you mean?  published
	from /srv/scalelite/lib/recording_importer.rb:33:in `block (3 levels) in import'
	from /srv/scalelite/lib/recording_importer.rb:25:in `each'
	from /srv/scalelite/lib/recording_importer.rb:25:in `block (2 levels) in import'
	from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	from /srv/scalelite/lib/recording_importer.rb:21:in `block in import'
	from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir' ...

Any help will be much appreciated.

**Comment by jfederico** [comment]
Yeah, this seems to be that you are missing the migration. Do you need 1.2 with protected recordings or just hoping that the issue with the root certificate was solved there? Because there are new images with amazonlinux for both 1.1 (`1.1.8.1`) and 1.2 (`1.2.0.1`).

As for the migration, it may have come to an odd state. You may need to revert and apply them again. This is pure rails, so, it may be time to read a bit on rails migrations.

As a shortcut, you can see the status
```
docker exec -i scalelite-api bundle exec rake db:migrate:status
```
And the output should be something like this:
```
   up     20181123180008  Init
   up     20210425184558  Create callback data
   up     20210630205630  Add protected to recordings
   up     20210725200414  Add publish updated to recordings
```

As I said, more likely you are missing the last migration, you may need to revert and apply again,
```
docker exec -i scalelite-api bundle exec rake db:migrate:down VERSION=20210725200414
docker exec -i scalelite-api bundle exec rake db:migrate VERSION=20210725200414
```

If that does not work, you may need to go one version up `20210630205630`

**Comment by panosva** [comment]
> That should solve the problem, but as you know it would also clear all the data. Instead can you do a `docker exec -i scalelite-api bundle exec rake db:rollback` and `docker exec -i scalelite-api bundle exec rake db:migrate` and post the output of both. Additionally can you also try restarting services after those steps.

I have tried rollback earlier on, it did not work either.
Thank you for your confirmation by recreating the database and tables everything is back to normal!!
