### ISSUE TITLE
404 error on recordings playback + Old Recording not show after upgrade to v1.2.0.1

### ISSUE THREAD

**Issue by morexzamani** [blindsidenetworks/scalelite#700]
Hi Scalelite development team (@ffdixon , @amalrails , @jfederico , @rabser )
I've faced a problem some days and unfortunately can't find anyone to solve it. Please help me.

I use Moodle to handle classes. My Scalelite server worked very well without any problem until I was updated it (If I`m not mistaken, from v1.1.7 to 1.2.0) one or two weeks ago. After that, my old recordings have gone from moodle recordings list and I have 404 error for new recordings that appear in the Moodle list after upgrade, 

For error 404 I found my recordings remain in the spool directory and scalelite-recording-importer is not working correctly 

(Note that I downgraded to v1.1.8.1, but the problem still exists!)

Please help me to return them back.

## Here is some reports:

**`nano /etc/default/scalelite`:**

```
URL_HOST=XXX.XXX.XXX
SECRET_KEY_BASE=XXXX
LOADBALANCER_SECRET=XXXXX
DATABASE_URL=postgresql://postgres:XXXXXXPASSWORD@XXXXIP:5432
REDIS_URL=redis://redis
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly
SCALELITE_TAG=v1.2.0.1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
POLLING_INTERVALL=2
```

**`docker ps`:**

```
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED         STATUS         PORTS                                                                      NAMES
XXXX7338a945   blindsidenetwks/scalelite:v1.2.0.1-poller               "bin/start-poller"       6 minutes ago   Up 6 minutes                                                                              scalelite-poller
XXXX623904cd   blindsidenetwks/scalelite:v1.2.0.1-recording-importer   "bin/start-recording…"   6 minutes ago   Up 6 minutes                                                                              scalelite-recording-importer
XXXX24978c8e   blindsidenetwks/scalelite:v1.2.0.1-nginx                "/etc/nginx/start -g…"   6 minutes ago   Up 6 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   scalelite-nginx
XXXX1462f564   blindsidenetwks/scalelite:v1.2.0.1-api                  "bin/start"              6 minutes ago   Up 6 minutes   3000/tcp                                                                   scalelite-api
XXXX81617a16   redis                                                   "docker-entrypoint.s…"   3 months ago    Up 41 hours    127.0.0.1:6379->6379/tcp                                                   redis
XXXXe2e35763   postgres                                                "docker-entrypoint.s…"   3 months ago    Up 41 hours    0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                  postgres
```

**`systemctl status scalelite-api.service scalelite-nginx.service scalelite-poller.service scalelite-recording-importer.service -l`:**

```
● scalelite-api.service - Scalelite API
   Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-10-09 16:59:33 +0330; 8s ago
  Process: 5207 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
  Process: 5187 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=0/SUCCESS)
  Process: 5172 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=0/SUCCESS)
  Process: 5158 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)
 Main PID: 5206 (docker)
    Tasks: 12
   Memory: 55.9M
   CGroup: /system.slice/scalelite-api.service
           └─5206 /usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=/mnt/scalelite-recordings/var/bigbluebutton,target=/var/bigbluebutton blindsidenetwks/scalelite:v1.2.0.1-api

Oct 09 16:59:40 my-scalelite-address.com docker[5206]: D, [2021-10-09T13:29:40.216024 #9] DEBUG -- :    (0.5ms)  SELECT pg_try_advisory_lock(1726294289930001330)
Oct 09 16:59:40 my-scalelite-address.com docker[5206]: D, [2021-10-09T13:29:40.236307 #9] DEBUG -- :    (1.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Oct 09 16:59:40 my-scalelite-address.com docker[5206]: D, [2021-10-09T13:29:40.246672 #9] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.7ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
Oct 09 16:59:40 my-scalelite-address.com docker[5206]: D, [2021-10-09T13:29:40.265240 #9] DEBUG -- :    (0.7ms)  SELECT pg_advisory_unlock(1726294289930001330)
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: Puma starting in single mode...
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: * Puma version: 5.3.1 (ruby 2.7.4-p191) ("Sweetnighter")
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: *  Min threads: 5
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: *  Max threads: 5
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: *  Environment: production
Oct 09 16:59:41 my-scalelite-address.com docker[5206]: *          PID: 11

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-10-09 16:59:36 +0330; 5s ago
  Process: 5476 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
  Process: 5354 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 5311 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 5235 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 5475 (docker)
    Tasks: 12
   Memory: 32.2M
   CGroup: /system.slice/scalelite-nginx.service
           └─5475 /usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,source=/mnt/scalelite-recordings/var/bigbluebutton/published,target=/var/bigbluebutton/published,readonly --mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly blindsidenetwks/scalelite:v1.2.0.1-nginx

Oct 09 16:59:36 my-scalelite-address.com docker[5354]: docker.io/blindsidenetwks/scalelite:v1.2.0.1-nginx
Oct 09 16:59:36 my-scalelite-address.com docker[5476]: Total reclaimed space: 0B
Oct 09 16:59:36 my-scalelite-address.com systemd[1]: Started Scalelite Nginx.
Oct 09 16:59:36 my-scalelite-address.com docker[5475]: Startup script was run as init, re-execing using tini.
Oct 09 16:59:36 my-scalelite-address.com docker[5475]: Generating templated nginx configuration...
Oct 09 16:59:36 my-scalelite-address.com docker[5475]: Using SSL configuration template.
Oct 09 16:59:36 my-scalelite-address.com docker[5475]: Starting nginx periodic reload process...
Oct 09 16:59:36 my-scalelite-address.com docker[5475]: Starting nginx...
Oct 09 16:59:38 my-scalelite-address.com docker[5475]: 195.211.46.234 - - [09/Oct/2021:13:29:38 +0000] "GET /bigbluebutton/api/getMeetingInfo?meetingID=XXXXXXXX4d700a21c2aa86ec6944091e18-54-184&checksum=d4925e4c39f538f105b0ff5bc02bd9488adbd7e8 HTTP/2.0" 502 150 "-" "MoodleBot/3.11 (+https://mymoodle.com)" "-"
Oct 09 16:59:38 my-scalelite-address.com docker[5475]: 2021/10/09 13:29:38 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 195.211.46.234, server: , request: "GET /bigbluebutton/api/getMeetingInfo?meetingID=XXXXXXXX4d700a21c2aa86ec6944091e18-54-184&checksum=d4925e4c39f538f105b0ff5bc02bd9488adbd7e8 HTTP/2.0", upstream: "http://172.18.0.4:3000/bigbluebutton/api/getMeetingInfo?meetingID=XXXXXXXX4d700a21c2aa86ec6944091e18-54-184&checksum=d4925e4c39f538f105b0ff5bc02bd9488adbd7e8", host: "my-scalelite-address.com"

● scalelite-poller.service - Scalelite Meeting Status Poller
   Loaded: loaded (/etc/systemd/system/scalelite-poller.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-10-09 16:59:36 +0330; 5s ago
  Process: 5588 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
  Process: 5375 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-poller (code=exited, status=0/SUCCESS)
  Process: 5307 ExecStartPre=/usr/bin/docker rm scalelite-poller (code=exited, status=0/SUCCESS)
  Process: 5234 ExecStartPre=/usr/bin/docker kill scalelite-poller (code=exited, status=1/FAILURE)
 Main PID: 5587 (docker)
    Tasks: 11
   Memory: 30.2M
   CGroup: /system.slice/scalelite-poller.service
           └─5587 /usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-poller --env-file /etc/default/scalelite --network scalelite blindsidenetwks/scalelite:v1.2.0.1-poller

Oct 09 16:59:40 my-scalelite-address.com docker[5587]: D, [2021-10-09T13:29:40.632791 #7] DEBUG -- : Polling Meeting id=XXXXXXXXXXXX3a585357b3030b4e12e72b457-20-28 on Server id=XXXXXXXX47e1-91d3-80506abc5db6
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: D, [2021-10-09T13:29:40.635806 #7] DEBUG -- : Polling Meeting id=XXXXXXXXXXXX9b4d700a21c2aa86ec6944091e18-53-268 on Server id=XXXXXXXX494e-9e52-c0ef3508777e
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: I, [2021-10-09T13:29:40.709269 #7]  INFO -- : Server id=XXXXXXXX494e-9e52-c0ef3508777e online load: 3.0
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: D, [2021-10-09T13:29:40.709534 #7] DEBUG -- : Polling Server id=XXXXXXXXX-4d05-a06c-4f0b7b63de97
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: I, [2021-10-09T13:29:40.727451 #7]  INFO -- : Server id=XXXXXXXX47e1-91d3-80506abc5db6 online load: 5.0
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: D, [2021-10-09T13:29:40.728863 #7] DEBUG -- : Polling Meeting id=XXXXXXXXXX49df909bc51448271a0f2f1198f72-101-357 on Server id=XXXXXXXX494e-9e52-c0ef3508777e
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: I, [2021-10-09T13:29:40.731783 #7]  INFO -- : Server id=XXXXXXXXXXX2c-4614-9443-ff2a5a190934 online load: unavailable
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: I, [2021-10-09T13:29:40.732072 #7]  INFO -- : Server id=XXXXXXXXXXX2-4581-bec7-292d6f964dc6 online load: 15.0
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: W, [2021-10-09T13:29:40.732242 #7]  WARN -- : Failed to check meeting id=XXXXXXXXXX3bebfb53a57e3b8c0df21272e8e5-45-117 status: Couldn't find Server with id=XXXXXXXXXe-4095-abe9-76215c9bb3be
Oct 09 16:59:40 my-scalelite-address.com docker[5587]: I, [2021-10-09T13:29:40.787379 #7]  INFO -- : Server id=97cc047b-292d-4d05-a06c-4f0b7b63de97 online load: 0.0

● scalelite-recording-importer.service - Scalelite Recording Importer
   Loaded: loaded (/etc/systemd/system/scalelite-recording-importer.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-10-09 16:59:36 +0330; 5s ago
  Process: 5502 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
  Process: 5376 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer (code=exited, status=0/SUCCESS)
  Process: 5310 ExecStartPre=/usr/bin/docker rm scalelite-recording-importer (code=exited, status=0/SUCCESS)
  Process: 5233 ExecStartPre=/usr/bin/docker kill scalelite-recording-importer (code=exited, status=1/FAILURE)
 Main PID: 5501 (docker)
    Tasks: 12
   Memory: 30.1M
   CGroup: /system.slice/scalelite-recording-importer.service
           └─5501 /usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-recording-importer --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=/mnt/scalelite-recordings/var/bigbluebutton,target=/var/bigbluebutton blindsidenetwks/scalelite:v1.2.0.1-recording-importer

Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-29.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-97.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-78.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-98.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-3.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-57.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-77.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-89.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-54.png
Oct 09 16:59:42 my-scalelite-address.com docker[5501]: presentation/XXXXXXXXc73e52102-1632896581703/presentation/XXXXXXXXac85439dcf722e6-1632896731384/slide-8.png
```

**and `docker exec -it scalelite-nginx cat /etc/bigbluebutton/nginx/playback.nginx`:**
```
location /playback/presentation/2.3 {
  root /var/bigbluebutton;
  try_files $uri /playback/presentation/2.3/index.html;
}
```

**`docker exec -it scalelite-nginx cat /etc/bigbluebutton/nginx/presentation.nginx`:**

```
location /playback/presentation/playback.html {
                return 301 /playback/presentation/0.81/playback.html?$query_string;
                # If you have recordings from 0.9.0 beta versions and are sure
                # that you will never want to play recordings made with
                # BigBlueButton 0.81, comment the line above and uncomment the
                # following line:
                #return 301 /playback/presentation/0.9.0/playback.html?$query_string;
        }

        location /playback/presentation/2.0/playback.html {
                return 301 /playback/presentation/2.3/$arg_meetingId?$query_string;
        }

        location /playback/presentation {
                root    /var/bigbluebutton;
                index  index.html index.htm;
        }

        location /presentation {
                root    /var/bigbluebutton/published;
                index  index.html index.htm;
        }
```

I opened an offline meeting in moodle and got the 404 error. when I was looking for the Meeting_ID file in Scalelite, I found it isn't present! then I check the spool directory:

**`ls /mnt/scalelite-recordings/var/bigbluebutton/spool/ | wc -l`:**
```
218
```

and I found there is an error in **`docker logs --tail 50 --follow --timestamps scalelite-recording-importer`:**
```
2021-10-09T13:31:04.103304077Z D, [2021-10-09T13:31:04.102993 #8] DEBUG -- :   Metadatum Load (0.8ms)  SELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 218], ["key", "bbb-origin-version"], ["LIMIT", 1]]
2021-10-09T13:31:04.104719134Z D, [2021-10-09T13:31:04.104306 #8] DEBUG -- : #<Metadatum id: 2831, recording_id: 218, key: "bbb-origin-version", value: "3.11.3 (Build: 20210913)">
2021-10-09T13:31:04.106922715Z D, [2021-10-09T13:31:04.106532 #8] DEBUG -- :   Metadatum Load (0.9ms)  SELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 218], ["key", "bbb-recording-tags"], ["LIMIT", 1]]
2021-10-09T13:31:04.108262435Z D, [2021-10-09T13:31:04.107916 #8] DEBUG -- : #<Metadatum id: 2832, recording_id: 218, key: "bbb-recording-tags", value: "">
2021-10-09T13:31:04.110463864Z D, [2021-10-09T13:31:04.110160 #8] DEBUG -- :   Metadatum Load (0.9ms)  SELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 218], ["key", "bbb-origin"], ["LIMIT", 1]]
2021-10-09T13:31:04.111747763Z D, [2021-10-09T13:31:04.111440 #8] DEBUG -- : #<Metadatum id: 2833, recording_id: 218, key: "bbb-origin", value: "Moodle">
2021-10-09T13:31:04.113920871Z D, [2021-10-09T13:31:04.113614 #8] DEBUG -- :   Metadatum Load (0.8ms)  SELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 218], ["key", "bbb-context-name"], ["LIMIT", 1]]
2021-10-09T13:31:04.115199472Z D, [2021-10-09T13:31:04.114928 #8] DEBUG -- : #<Metadatum id: 2834, recording_id: 218, key: "bbb-context-name", value: "XXXXClassNameXXXXX">
2021-10-09T13:31:04.118830903Z D, [2021-10-09T13:31:04.118446 #8] DEBUG -- :   PlaybackFormat Load (1.0ms)  SELECT "playback_formats".* FROM "playback_formats" WHERE "playback_formats"."recording_id" = $1 AND "playback_formats"."format" = $2 ORDER BY "playback_formats"."format" ASC LIMIT $3  [["recording_id", 218], ["format", "presentation"], ["LIMIT", 1]]
2021-10-09T13:31:04.120828290Z D, [2021-10-09T13:31:04.120528 #8] DEBUG -- : #<PlaybackFormat id: 218, recording_id: 218, format: "presentation", url: "/playback/presentation/2.3/1d967b02ce2bae0b714ddb2...", length: 77, processing_time: nil>
2021-10-09T13:31:04.124244982Z D, [2021-10-09T13:31:04.123948 #8] DEBUG -- :   Thumbnail Load (1.0ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3  [["playback_format_id", 218], ["sequence", 0], ["LIMIT", 1]]
2021-10-09T13:31:04.128750121Z D, [2021-10-09T13:31:04.128323 #8] DEBUG -- :   Thumbnail Load (1.0ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3  [["playback_format_id", 218], ["sequence", 1], ["LIMIT", 1]]
2021-10-09T13:31:04.132962520Z D, [2021-10-09T13:31:04.132563 #8] DEBUG -- :   Thumbnail Load (1.0ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3  [["playback_format_id", 218], ["sequence", 2], ["LIMIT", 1]]
2021-10-09T13:31:04.136672583Z D, [2021-10-09T13:31:04.136359 #8] DEBUG -- :   Thumbnail Load (1.0ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC  [["playback_format_id", 218]]
2021-10-09T13:31:04.139362719Z D, [2021-10-09T13:31:04.139043 #8] DEBUG -- :    (1.1ms)  COMMIT
2021-10-09T13:31:04.254706203Z E, [2021-10-09T13:31:04.254131 #8] ERROR -- : Failed to import recording: undefined method `publish_updated' for #<Recording:0x00007ff86b472a50>
2021-10-09T13:31:04.254794932Z Did you mean?  published
2021-10-09T13:31:04.254819274Z D, [2021-10-09T13:31:04.254350 #8] DEBUG -- : Starting file monitor…
```

**`docker exec -i scalelite-api bundle exec rake db:rollback`:**
```
D, [2021-10-07T20:25:01.791328 #67] DEBUG -- :    (1.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2021-10-07T20:25:01.793171 #67] DEBUG -- :    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2021-10-07T20:25:01.794855 #67] DEBUG -- :    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2021-10-07T20:25:01.816682 #67] DEBUG -- :    (0.4ms)  SELECT pg_try_advisory_lock(1726294289930001330)
D, [2021-10-07T20:25:01.817820 #67] DEBUG -- :    (0.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2021-10-07T20:25:01.818078 #67]  INFO -- : Migrating to AddPublishUpdatedToRecordings (20210725200414)
== 20210725200414 AddPublishUpdatedToRecordings: reverting ====================
-- remove_column(:recordings, :publish_updated, :boolean, {:default=>false})
D, [2021-10-07T20:25:01.823419 #67] DEBUG -- :    (0.4ms)  BEGIN
D, [2021-10-07T20:25:01.824993 #67] DEBUG -- :    (1.3ms)  ALTER TABLE "recordings" DROP COLUMN "publish_updated"
D, [2021-10-07T20:25:01.825606 #67] DEBUG -- :    (0.4ms)  ROLLBACK
D, [2021-10-07T20:25:01.826373 #67] DEBUG -- :    (0.5ms)  SELECT pg_advisory_unlock(1726294289930001330)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "publish_updated" of relation "recordings" does not exist
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
...
...
```

and when I run migrate **`docker exec -t scalelite-api bundle exec rake db:migrate`:**

```
D, [2021-10-09T13:44:00.038605 #28] DEBUG -- :    (0.7ms)  SELECT pg_try_advisory_lock(1726294289930001330)
D, [2021-10-09T13:44:00.053765 #28] DEBUG -- :    (2.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2021-10-09T13:44:00.068368 #28] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.3ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2021-10-09T13:44:00.087927 #28] DEBUG -- :    (1.1ms)  SELECT pg_advisory_unlock(1726294289930001330)
```

**`docker exec -i scalelite-api bundle exec rake db:migrate:status`:**
```
database: scalelite

 Status   Migration ID    Migration Name
--------------------------------------------------
D, [2021-10-09T13:44:24.458995 #36] DEBUG -- :    (1.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   up     20181123180008  Init
   up     20210425184558  Create callback data
   up     20210630205630  Add protected to recordings
   up     20210725200414  Add publish updated to recordings
```

## At the end, my problems that still exist are:

1. ### My old records don't show in moodle
2. ### Records playback page has 404 error

**Comment by rabser** [comment]
Only for transparency, i'm not part of the DevTeam of Scalelite, i'm only a SL user like you.

**Comment by MrCapitalist** [comment]
> Hello, good Morning
> 
> For what is being displayed, the problem is found in the BD for both its videos and the 404 error.
> ....
> Once the problem is solved, your videos found in Spool will begin to decompress and you will be able to view without the 404 error.

Hi @WinterJV 
Thanks for your solution but it's not a good idea but I want my old database's values and recording. 
I'm waiting for @amalrails to check the database structure completely and introduce a clean solution to resolve these problems in this new version.

**Comment by amalrails** [comment]
@MrCapitalist are you able to playback your older recordings with previous versions like v1.1.8 ?

**Comment by MrCapitalist** [comment]
> v1.1.8

No, I can't. there isn't any record in the list of records in moodle. I've checked it now.

**Comment by jfederico** [comment]
Read my last post again. The answer is there...
