### ISSUE TITLE
Scalelite - Error 500

### ISSUE THREAD

**Issue by alizamanir** [blindsidenetworks/scalelite#748]
Hello

I have Scalelite 1.3.2.1 on one of my servers.
after 3~4 hour of working of the scalelite, the requests return Error 500 as follow:

<hash>
<status type="integer">500</status>
<error>Internal Server Error</error>
</hash>

as I checked the scalelite-api docker logs, the following error appears there:

[06035fc6-108a-47c5-a03e-2c8692596778]
[06035fc6-108a-47c5-a03e-2c8692596778] app/controllers/bigbluebutton_api_controller.rb:296:in `get_recordings'
I, [2022-01-21T20:35:08.679255 #11]  INFO -- : [70b0d2fd-f0d5-4d74-858a-00715b8b678f] Started GET "/bigbluebutton//api/getRecordings?meetingID=34165&checksum=97b9378f501d12c3a68680eb33dd27bdfd73153c" for 172.18.0.4 at 2022-01-21 20:35:08 +0000
I, [2022-01-21T20:35:08.680243 #11]  INFO -- : [70b0d2fd-f0d5-4d74-858a-00715b8b678f] Processing by BigBlueButtonApiController#get_recordings as XML
I, [2022-01-21T20:35:08.680320 #11]  INFO -- : [70b0d2fd-f0d5-4d74-858a-00715b8b678f]   Parameters: {"meetingID"=>"34165", "checksum"=>"97b9378f501d12c3a68680eb33dd27bdfd73153c"}
I, [2022-01-21T20:35:08.683080 #11]  INFO -- : [70b0d2fd-f0d5-4d74-858a-00715b8b678f] Completed 500 Internal Server Error in 3ms (Allocations: 657)
F, [2022-01-21T20:35:08.684782 #11] FATAL -- : [70b0d2fd-f0d5-4d74-858a-00715b8b678f]
[70b0d2fd-f0d5-4d74-858a-00715b8b678f] PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "172.16.9.9" and accepting
        TCP/IP connections on port 5432?
):
[70b0d2fd-f0d5-4d74-858a-00715b8b678f]
[70b0d2fd-f0d5-4d74-858a-00715b8b678f] app/controllers/bigbluebutton_api_controller.rb:296:in `get_recordings'
I, [2022-01-21T20:35:08.715311 #11]  INFO -- : [7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7] Started GET "/bigbluebutton//api/getRecordings?meetingID=34186&checksum=278f9b0f962c7020977967458ab30655db722c07" for 172.18.0.4 at 2022-01-21 20:35:08 +0000
I, [2022-01-21T20:35:08.716377 #11]  INFO -- : [7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7] Processing by BigBlueButtonApiController#get_recordings as XML
I, [2022-01-21T20:35:08.716457 #11]  INFO -- : [7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7]   Parameters: {"meetingID"=>"34186", "checksum"=>"278f9b0f962c7020977967458ab30655db722c07"}
I, [2022-01-21T20:35:08.718618 #11]  INFO -- : [7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7] Completed 500 Internal Server Error in 2ms (Allocations: 657)
F, [2022-01-21T20:35:08.719667 #11] FATAL -- : [7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7]
[7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7] PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "172.16.9.9" and accepting
        TCP/IP connections on port 5432?
):
[7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7]
[7b627a52-d5a3-4e64-a9ae-6b6bbc84a1f7] app/controllers/bigbluebutton_api_controller.rb:296:in `get_recordings'
I, [2022-01-21T20:35:08.737927 #11]  INFO -- : [0ed66e71-04f8-4f32-9e09-3e9f626023c4] Started GET "/bigbluebutton//api/getRecordings?meetingID=34210&checksum=1566e43a514515f066d1ccb8549fe0595134f15f" for 172.18.0.4 at 2022-01-21 20:35:08 +0000
I, [2022-01-21T20:35:08.738887 #11]  INFO -- : [0ed66e71-04f8-4f32-9e09-3e9f626023c4] Processing by BigBlueButtonApiController#get_recordings as XML
I, [2022-01-21T20:35:08.738961 #11]  INFO -- : [0ed66e71-04f8-4f32-9e09-3e9f626023c4]   Parameters: {"meetingID"=>"34210", "checksum"=>"1566e43a514515f066d1ccb8549fe0595134f15f"}
I, [2022-01-21T20:35:08.740716 #11]  INFO -- : [0ed66e71-04f8-4f32-9e09-3e9f626023c4] Completed 500 Internal Server Error in 2ms (Allocations: 657)
F, [2022-01-21T20:35:08.741714 #11] FATAL -- : [0ed66e71-04f8-4f32-9e09-3e9f626023c4]
[0ed66e71-04f8-4f32-9e09-3e9f626023c4] PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "172.16.9.9" and accepting
        TCP/IP connections on port 5432?
):
[0ed66e71-04f8-4f32-9e09-3e9f626023c4]
[0ed66e71-04f8-4f32-9e09-3e9f626023c4] app/controllers/bigbluebutton_api_controller.rb:296:in `get_recordings'
I, [2022-01-21T20:35:08.759267 #11]  INFO -- : [a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08] Started GET "/bigbluebutton//api/getRecordings?meetingID=34212&checksum=3d48ec9152979ea2a1b4e5bf63b578d309f1dd63" for 172.18.0.4 at 2022-01-21 20:35:08 +0000
I, [2022-01-21T20:35:08.760134 #11]  INFO -- : [a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08] Processing by BigBlueButtonApiController#get_recordings as XML
I, [2022-01-21T20:35:08.760210 #11]  INFO -- : [a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08]   Parameters: {"meetingID"=>"34212", "checksum"=>"3d48ec9152979ea2a1b4e5bf63b578d309f1dd63"}
I, [2022-01-21T20:35:08.762000 #11]  INFO -- : [a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08] Completed 500 Internal Server Error in 2ms (Allocations: 657)
F, [2022-01-21T20:35:08.762905 #11] FATAL -- : [a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08]
[a121d0b8-ba5f-4b9a-8e0c-e2fb26c93b08] PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "172.16.9.9" and accepting
        TCP/IP connections on port 5432?
):

the issue resolves only if I reboot the scalelite server and restarting the services (UFW, scalelite-api, scalelite-nginex) have no effect.

Thanks

**Comment by rabser** [comment]
The important llines are:
 ```
Is the server running on host "172.16.9.9" and accepting
TCP/IP connections on port 5432?
```
Your postgres database does not work anymore... check why looking at pg logs, it's not a matter of scalelite.

**Comment by alizamanir** [comment]
the 172.16.9.9 is the internal IP of the scalelite,
when I check the pgsql, the psql is up and running.

**Comment by rabser** [comment]
The daemon up&running is not enough, double check the postgres server errors, maybe it's locked by running out of connections or anything else.

**Comment by alizamanir** [comment]
Hello

As I double checked, the PostgreSQL is up and running but it refuse the connections and making a "service postgresql restart" resolves the 500 error for couple of hours.

I checked the pg-hba.conf and its allowed connection for any host using:

host    all             all             all                     trust

also it listens to all connections (postgresql.conf) using

listen_addresses = '*'

have you any suggestion for trouble shooting this issue?

Thanks

**Comment by rabser** [comment]
Check your PostgreSQL error log to understand what is happening. The locations may vary depending on your o.s. and type of installation on PostgreSQL. Probably the server is locking itself on many logon errors, or anything other critical runtime condition, but without debugging the database, any suggestion is a pure thinking exercise.
