### ISSUE TITLE
Error in the scalelite_batch_import.sh script on BigBlueButton 2.5.2 server

### ISSUE THREAD

**Issue by Melkin1968** [blindsidenetworks/scalelite#796]
**Describe the bug**
I`ve got an error in attempt to use scalelite_batch_import.sh on BigBlueButton 2.5.2 server. Could you please help me?
root@bbb1-focal:/home/ubuntu/Oleg_install# ./scalelite_batch_import.sh
Traceback (most recent call last):
        8: from ./post_publish/scalelite_post_publish.rb:23:in `<main>'
        7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)

**To Reproduce**
Install the script on clear installed BigBlueButton server version >= 2.5

**Comment by flyinghuman** [comment]
same here. any suggestions to fix this?

**Comment by flyinghuman** [comment]
Seems that the install-script is missing some Packages for BBB 2.5:

This fixed it for me:
```
apt install ruby2.7-dev libsystemd-dev
gem install redis builder nokogiri loofah open4 absolute_time journald-logger
```

**Comment by Melkin1968** [comment]
Dear @flyinghuman , thank you a lot for your suggestion. It helps me.

**Comment by amg-web** [comment]
@flyinghuman 
till now no changes here https://github.com/bigbluebutton/bbb-install/issues/539
I think it would be better to change to modify scalelite_post_publish.rb not to use this dependencies as they are not actually required for the script and move **published_dir** setting to scalelite.yml

Also we'll need to edit logging section:
Currently I have following error after disabling #require File.expand_path('../../lib/recordandplayback', __dir__)
`Traceback (most recent call last):
./post_publish/scalelite_post_publish.rb:25:in `<main>': uninitialized constant Logger (NameError)
`

**Comment by dmtrhfr** [comment]
Experience this on 2.6 as well

**Comment by ffdixon** [comment]
@dmtrhfr

> apt install ruby2.7-dev libsystemd-dev
> gem install redis builder nokogiri loofah open4 absolute_time journald-logger

Did the above work for you?

If so, since everyone wouldn't be using the `scalelite_batch_import.sh` script, rather then add them to the core of BigBlueButton install, it would be better to add the above to the ScaleLite docs as part of the setup.

**Comment by lonesomewalker** [comment]
+1
This would be nice, because we just had a customer calling us because he can't get his recordings synced.
