### ISSUE TITLE
Scalelite recordings transfer not working, manually or automatically

### ISSUE THREAD

**Issue by hamedunik** [blindsidenetworks/scalelite#806]
**Describe the bug**
Traceback (most recent call last):
        8: from ./post_publish/scalelite_post_publish.rb:23:in `<main>'
        7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)

**To Reproduce**
install bbb 2.5
install scalelite
make folders and set permissions. download scalelite_post_publish.rb, scalelite_batch_import.sh and copy to specified folders
chmod the files scalelite_batch_import.sh
run scalelite_batch_import.sh

***Deployment:***
2. Versions: bbb 2.5 and latest scalelite
3. Tools used: terminal

recording is produced in bbb server and accessible. but not moved to mnt/scalelite-recordings folder and running batch file manually encounters error

**Comment by hamedunik** [comment]
i've tested again bbb 2.4 in ubuntu 18.04 and no problem. again installed bbb 2.5 in ubuntu 20.04 and again have above problem!
