### ISSUE TITLE
Warnings when disable/enable Conference-Nodes

### ISSUE THREAD

**Issue by mstruminski** [blindsidenetworks/scalelite#867]
**Describe the bug**
It is a warning, when I enable/disable a conference-node.
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.9.0/lib/redis/namespace.rb:479:in `call_with_namespace')

**To Reproduce**
bundle exec rake servers:enable[ID-OF-BBB-CONFNODE]
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.9.0/lib/redis/namespace.rb:479:in `call_with_namespace')

***Deployment:***
1. Deployment: the alternate docker-compose one
2. Versions: Scalelite 1.3.5.2

***Steps to reproduce the behavior:***

1. 'docker exec -it scalelite-api /bin/bash'
2. 'bundle exec rake servers:enable[85615192-82dd-44c7-9533-2d63b081de0a]'
3. 'bundle exec rake servers:disable[85615192-82dd-44c7-9533-2d63b081de0a]'

**Screenshots**

![Bildschirm­foto 2022-12-08 um 09 29 19](https://user-images.githubusercontent.com/100774169/206397522-40ddcf1c-9a92-4183-9b34-929213e6c54d.png)

**Comment by dirk-hl** [comment]
This bug is still present in version 1.4.

**Comment by farhatahmad** [comment]
Will be fixed by https://github.com/blindsidenetworks/scalelite/pull/904
