### ISSUE TITLE
rake db:migrate error

### ISSUE THREAD

**Issue by flyinghuman** [blindsidenetworks/scalelite#961]
Hello Everyone, i tried to update scalelite to latest v1 Release today from Version 1.3.4 but the db:migrate task did not migrate the db successfully:

```
docker exec -it scalelite-api rake db:migrate
D, [2023-06-08T11:45:33.048783 #32] DEBUG -- :    (0.1ms)  SELECT pg_try_advisory_lock(1726294289930001330)
D, [2023-06-08T11:45:33.053353 #32] DEBUG -- :    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2023-06-08T11:45:33.053922 #32]  INFO -- : Migrating to ChangeRecordings (20230418211340)
== 20230418211340 ChangeRecordings: migrating =================================
-- change_column_null(:recordings, :publish_updated, false)
D, [2023-06-08T11:45:33.055002 #32] DEBUG -- :   TRANSACTION (0.1ms)  BEGIN
D, [2023-06-08T11:45:33.055460 #32] DEBUG -- :    (0.4ms)  ALTER TABLE "recordings" ALTER COLUMN "publish_updated" SET NOT NULL
   -> 0.0007s
-- change_column_null(:recordings, :protected, false)
D, [2023-06-08T11:45:33.056293 #32] DEBUG -- :    (0.5ms)  ALTER TABLE "recordings" ALTER COLUMN "protected" SET NOT NULL
D, [2023-06-08T11:45:33.056530 #32] DEBUG -- :   TRANSACTION (0.1ms)  ROLLBACK
D, [2023-06-08T11:45:33.056901 #32] DEBUG -- :    (0.2ms)  SELECT pg_advisory_unlock(1726294289930001330)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: FEHLER:  Spalte »protected« von Relation »recordings« enthält NULL-Werte
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `exec'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `block (2 levels) in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:420:in `change_column_null'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:929:in `block in method_missing'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `block in say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:918:in `method_missing'
/srv/scalelite/db/migrate/20230418211340_change_recordings.rb:7:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `public_send'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `exec_migration'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:850:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:849:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1037:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `block in ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:209:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1086:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1061:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'

Caused by:
ActiveRecord::NotNullViolation: PG::NotNullViolation: FEHLER:  Spalte »protected« von Relation »recordings« enthält NULL-Werte
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `exec'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `block (2 levels) in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:420:in `change_column_null'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:929:in `block in method_missing'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `block in say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:918:in `method_missing'
/srv/scalelite/db/migrate/20230418211340_change_recordings.rb:7:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `public_send'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `exec_migration'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:850:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:849:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1037:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `block in ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:209:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1086:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1061:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'

Caused by:
PG::NotNullViolation: FEHLER:  Spalte »protected« von Relation »recordings« enthält NULL-Werte
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `exec'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `block (2 levels) in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block in execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `execute'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:420:in `change_column_null'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:929:in `block in method_missing'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `block in say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:897:in `say_with_time'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:918:in `method_missing'
/srv/scalelite/db/migrate/20230418211340_change_recordings.rb:7:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `public_send'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:870:in `exec_migration'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:850:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:849:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1037:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `block in ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:209:in `transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `ddl_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `block in migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1086:in `up'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1061:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `each'
/srv/scalelite/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

What can i do in this case?

(For now i'm back to 1.3.4)

Thanks!

**Comment by ffdixon** [comment]
Hmm ... could you manually add the column "publish_updated" and try running the migrations again.

**Comment by flyinghuman** [comment]
i solved it by myself:

`update recordings set protected='f' where protected is null;`

after changing the values in column protected to other values that null it worked.

**Comment by ffdixon** [comment]
Thanks for sharing this -- it will definitely help others.
